# Generated by Django 2.2.16 on 2020-10-13 10:11

import markupfield.fields
from django.db import migrations, models

import LZK.utils
import LZK.validators


class Migration(migrations.Migration):

    dependencies = [
        ("LZK", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="notes",
            field=markupfield.fields.MarkupField(
                rendered_field=True, verbose_name="Notes"
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="logo",
            field=models.FileField(
                upload_to=LZK.utils.Uuid4Upload,
                validators=[
                    LZK.validators.FileValidator(
                        extensions=["svg", "webp"],
                        mimetypes=["image/svg+xml", "image/webp"],
                    )
                ],
            ),
        ),
    ]
