# Generated by Django 2.2.16 on 2020-10-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LZK", "0002_auto_20201013_1011"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="text",
            name="_body_rendered",
        ),
        migrations.RemoveField(
            model_name="text",
            name="body_markup_type",
        ),
        migrations.AlterField(
            model_name="text",
            name="body",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="text",
            name="placement",
            field=models.CharField(
                choices=[
                    ("abilities", "Abilities"),
                    ("symptoms", "Symptoms"),
                    ("skills", "Skills"),
                    ("homepage", "Homepage"),
                    ("feedback-email", "Feedback (Email)"),
                ],
                default="abilities",
                max_length=32,
            ),
        ),
    ]
