# Generated by Django 2.2.17 on 2020-11-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LZK", "0005_auto_20201016_1032"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slide",
            name="_description_rendered",
        ),
        migrations.RemoveField(
            model_name="slide",
            name="description",
        ),
        migrations.RemoveField(
            model_name="slide",
            name="description_markup_type",
        ),
    ]
