# Generated by Django 2.2.17 on 2021-02-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LZK", "0006_auto_20201109_0946"),
    ]

    operations = [
        migrations.AddField(
            model_name="download",
            name="top",
            field=models.BooleanField(default=False, verbose_name="Top-Download"),
        ),
    ]
