# Generated by Django 2.2.17 on 2021-02-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LZK", "0007_download_top"),
    ]

    operations = [
        migrations.AddField(
            model_name="download",
            name="icon",
            field=models.TextField(default="file-o"),
        ),
    ]
