# Generated by Django 3.2.12 on 2022-03-03 18:30

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LZK", "0009_auto_20220212_1739"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from=["name"]
            ),
        ),
    ]
