# Generated by Django 3.2.12 on 2022-03-09 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LZK', '0010_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='rolemodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LZK.rolemodel'),
        ),
    ]
